name: Sample Pipeline
run-name: ${{ github.actor }} is running pipeline on ${{ github.repository }}
on: 
  pull_request:
    types: [closed]
    branches:
      - main     
jobs: 
  build:
    runs-on: ubuntu-latest
    environment: Production Dev Org
    steps:
      # Checkout the Source code from the latest commit
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install NPM
        run: |
          npm install
      # Install the SFDX CLI using npm command
      - name: Install the SFDX CLI
        run: |
          npm install sfdx-cli --global
          sfdx force --help
          
      - name: Install the sfdx-git-delta plugin
        run: |
          echo 'y' | sfdx plugins:install sfdx-git-delta
          
      - name: Authenticate Salesforce ORG
        run: |
          sfdx force:auth:jwt:grant --clientid 3MVG9pRzvMkjMb6mkMsAy61yRTBStzZUxz8ifciP17hhwIzNNwgQ3yyeiU1po2LofYkP3iyHZM24dz5aCmM5_ --jwtkeyfile assets/server.key --username vsanthosh@resilient-otter-go0gxs.com --setdefaultdevhubusername -a HubOrg --instanceurl https://login.salesforce.com   
      
      - name: Check deployment status
        id: check_status
        run: |
          deployment_status=$(sfdx force:data:soql:query --query "SELECT Id, Status, StartDate, CompletedDate, CreatedBy.Name FROM DeployRequest WHERE CreatedBy.Name='Subramanyam Kamath' ORDER BY CompletedDate DESC LIMIT 1" --usetoolingapi --json | jq -r '.result.records[0].Status')
          echo "Deployment Status: $deployment_status"
          if [ "$deployment_status" == "Failed" ]; then
            echo "Deployment failed, checking again in 5 minutes"
            exit 1
          fi
          if [ "$deployment_status" == "Succeeded" ]; then
            echo "Deployment passed, scheduling job in Salesforce org"
            sfdx force:apex:execute -u my-hub -f ./path/to/apex-script
          fi
