name: Deployment Status Check

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-deployment-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli@latest
      - name: Authenticate with Salesforce CLI
        run: |
          sfdx auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile ${{ secrets.SF_JWT_KEY_FILE }} --username ${{ secrets.SF_USERNAME }} --setdefaultdevhubusername --setalias my-hub
      - name: Check deployment status
        id: check_status
        run: |
          deployment_status=$(sfdx force:data:soql:query --query "SELECT Id, Status, StartDate, CompletedDate, CreatedBy.Name FROM DeployRequest WHERE CreatedBy.Name='Subramanyam Kamath' ORDER BY CompletedDate DESC LIMIT 1" --usetoolingapi --json | jq -r '.result.records[0].Status')
          echo "Deployment Status: $deployment_status"
          if [ "$deployment_status" == "Failed" ]; then
            echo "Deployment failed, checking again in 5 minutes"
            exit 1
          fi
          if [ "$deployment_status" == "Succeeded" ]; then
            echo "Deployment passed, scheduling job in Salesforce org"
            sfdx force:apex:execute -u my-hub -f ./path/to/apex-script
          fi
