name: Salesforce Deployment Checker

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  push:
    branches-ignore:
      - '*'  # Ignore pushes to branches
    tags-ignore:
      - '*'  # Ignore pushes to tags
  pull_request:
    branches-ignore:
      - '*'  # Ignore pull requests to branches
    tags-ignore:
      - '*'  # Ignore pull requests to tags

jobs:
  deployment_checker:
    if: github.actor == 'subramanyamkamath'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          sudo ./sfdx-cli/install

      - name: Login to Salesforce
        run: |
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CLIENT_ID }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername --setalias my-hub-org

      - name: Check Deployment Status
        id: deployment_status
        run: |
          sfdx force:mdapi:deploy:report -i <deployment_id> --json > deployment_status.json

      - name: Wait for 5 minutes
        run: sleep 300

      - name: Check Deployment Status Again
        if: steps.deployment_status.outputs.status != 'success'
        run: |
          sfdx force:mdapi:deploy:report -i <deployment_id> --json > deployment_status.json

      - name: Final Deployment Status
        run: |
          echo "Deployment Status: ${{ steps.deployment_status.outputs.status }}"
