name: Deployment Status Check

on: [push]

jobs:
  check-deployment-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli@latest
          
      - name: Authenticate Salesforce ORG
        run: |
          sfdx force:auth:jwt:grant --clientid 3MVG9pRzvMkjMb6mkMsAy61yRTBStzZUxz8ifciP17hhwIzNNwgQ3yyeiU1po2LofYkP3iyHZM24dz5aCmM5_ --jwtkeyfile assets/server.key --username vsanthosh@resilient-otter-go0gxs.com --setdefaultdevhubusername -a HubOrg --instanceurl https://login.salesforce.com 
          
      - name: Check deployment status
        id: check_status
        run: |
          deployment_status=$(sfdx force:data:soql:query --query "SELECT Id, Status, StartDate, CompletedDate, CreatedBy.Name FROM DeployRequest WHERE CreatedBy.Name='Subramanyam Kamath' ORDER BY CompletedDate DESC LIMIT 1" --usetoolingapi --json | jq -r '.result.records[0].Status')
          echo "Deployment Status: $deployment_status"
          if [ "$deployment_status" == "Failed" ]; then
            echo "Deployment failed, checking again in 5 minutes"
            exit 1
          fi
          if [ "$deployment_status" == "Succeeded" ]; then
            echo "Deployment passed, scheduling job in Salesforce org"
            sfdx force:apex:execute -u my-hub -f ./path/to/apex-script
          fi
